/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/_shop'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ShopIndexRouteImport } from './routes/_shop.index'
import { Route as ShopAboutRouteImport } from './routes/_shop.about'
import { Route as ShopCartRouteImport } from './routes/_shop.cart'
import { Route as ShopCategoriesRouteImport } from './routes/_shop.categories'
import { Route as ShopCheckoutRouteImport } from './routes/_shop.checkout'
import { Route as ShopContactRouteImport } from './routes/_shop.contact'
import { Route as ShopLoginRouteImport } from './routes/_shop.login'
import { Route as ShopNewArrivalsRouteImport } from './routes/_shop.new-arrivals'
import { Route as ShopProfileRouteImport } from './routes/_shop.profile'
import { Route as ShopRefundPolicyRouteImport } from './routes/_shop.refund-policy'
import { Route as ShopSearchRouteImport } from './routes/_shop.search'
import { Route as ShopShippingPolicyRouteImport } from './routes/_shop.shipping-policy'
import { Route as ShopTermsRouteImport } from './routes/_shop.terms'
import { Route as ShopTrackOrderRouteImport } from './routes/_shop.track-order'
import { Route as ShopWishlistRouteImport } from './routes/_shop.wishlist'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as ShopCategorySlugRouteImport } from './routes/_shop.category.$slug'
import { Route as ShopOrderSuccessIdRouteImport } from './routes/_shop.order-success.$id'
import { Route as ShopProductIdRouteImport } from './routes/_shop.product.$id'

const ShopRoute = ShopRouteImport.update({
  id: '/_shop',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const ShopAboutRoute = ShopAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCartRoute = ShopCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCategoriesRoute = ShopCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCheckoutRoute = ShopCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => ShopRoute,
} as any)
const ShopContactRoute = ShopContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => ShopRoute,
} as any)
const ShopLoginRoute = ShopLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => ShopRoute,
} as any)
const ShopNewArrivalsRoute = ShopNewArrivalsRouteImport.update({
  id: '/new-arrivals',
  path: '/new-arrivals',
  getParentRoute: () => ShopRoute,
} as any)
const ShopProfileRoute = ShopProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ShopRoute,
} as any)
const ShopRefundPolicyRoute = ShopRefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => ShopRoute,
} as any)
const ShopSearchRoute = ShopSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ShopRoute,
} as any)
const ShopShippingPolicyRoute = ShopShippingPolicyRouteImport.update({
  id: '/shipping-policy',
  path: '/shipping-policy',
  getParentRoute: () => ShopRoute,
} as any)
const ShopTermsRoute = ShopTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => ShopRoute,
} as any)
const ShopTrackOrderRoute = ShopTrackOrderRouteImport.update({
  id: '/track-order',
  path: '/track-order',
  getParentRoute: () => ShopRoute,
} as any)
const ShopWishlistRoute = ShopWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => ShopRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const ShopCategorySlugRoute = ShopCategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => ShopRoute,
} as any)
const ShopOrderSuccessIdRoute = ShopOrderSuccessIdRouteImport.update({
  id: '/order-success/$id',
  path: '/order-success/$id',
  getParentRoute: () => ShopRoute,
} as any)
const ShopProductIdRoute = ShopProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => ShopRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShopIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/about': typeof ShopAboutRoute
  '/cart': typeof ShopCartRoute
  '/categories': typeof ShopCategoriesRoute
  '/checkout': typeof ShopCheckoutRoute
  '/contact': typeof ShopContactRoute
  '/login': typeof ShopLoginRoute
  '/new-arrivals': typeof ShopNewArrivalsRoute
  '/profile': typeof ShopProfileRoute
  '/refund-policy': typeof ShopRefundPolicyRoute
  '/search': typeof ShopSearchRoute
  '/shipping-policy': typeof ShopShippingPolicyRoute
  '/terms': typeof ShopTermsRoute
  '/track-order': typeof ShopTrackOrderRoute
  '/wishlist': typeof ShopWishlistRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/': typeof AdminIndexRoute
  '/category/$slug': typeof ShopCategorySlugRoute
  '/order-success/$id': typeof ShopOrderSuccessIdRoute
  '/product/$id': typeof ShopProductIdRoute
}
export interface FileRoutesByTo {
  '/about': typeof ShopAboutRoute
  '/cart': typeof ShopCartRoute
  '/categories': typeof ShopCategoriesRoute
  '/checkout': typeof ShopCheckoutRoute
  '/contact': typeof ShopContactRoute
  '/login': typeof ShopLoginRoute
  '/new-arrivals': typeof ShopNewArrivalsRoute
  '/profile': typeof ShopProfileRoute
  '/refund-policy': typeof ShopRefundPolicyRoute
  '/search': typeof ShopSearchRoute
  '/shipping-policy': typeof ShopShippingPolicyRoute
  '/terms': typeof ShopTermsRoute
  '/track-order': typeof ShopTrackOrderRoute
  '/wishlist': typeof ShopWishlistRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/': typeof ShopIndexRoute
  '/admin': typeof AdminIndexRoute
  '/category/$slug': typeof ShopCategorySlugRoute
  '/order-success/$id': typeof ShopOrderSuccessIdRoute
  '/product/$id': typeof ShopProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shop': typeof ShopRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/_shop/about': typeof ShopAboutRoute
  '/_shop/cart': typeof ShopCartRoute
  '/_shop/categories': typeof ShopCategoriesRoute
  '/_shop/checkout': typeof ShopCheckoutRoute
  '/_shop/contact': typeof ShopContactRoute
  '/_shop/login': typeof ShopLoginRoute
  '/_shop/new-arrivals': typeof ShopNewArrivalsRoute
  '/_shop/profile': typeof ShopProfileRoute
  '/_shop/refund-policy': typeof ShopRefundPolicyRoute
  '/_shop/search': typeof ShopSearchRoute
  '/_shop/shipping-policy': typeof ShopShippingPolicyRoute
  '/_shop/terms': typeof ShopTermsRoute
  '/_shop/track-order': typeof ShopTrackOrderRoute
  '/_shop/wishlist': typeof ShopWishlistRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/_shop/': typeof ShopIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_shop/category/$slug': typeof ShopCategorySlugRoute
  '/_shop/order-success/$id': typeof ShopOrderSuccessIdRoute
  '/_shop/product/$id': typeof ShopProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/contact'
    | '/login'
    | '/new-arrivals'
    | '/profile'
    | '/refund-policy'
    | '/search'
    | '/shipping-policy'
    | '/terms'
    | '/track-order'
    | '/wishlist'
    | '/admin/categories'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/'
    | '/category/$slug'
    | '/order-success/$id'
    | '/product/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/contact'
    | '/login'
    | '/new-arrivals'
    | '/profile'
    | '/refund-policy'
    | '/search'
    | '/shipping-policy'
    | '/terms'
    | '/track-order'
    | '/wishlist'
    | '/admin/categories'
    | '/admin/orders'
    | '/admin/products'
    | '/'
    | '/admin'
    | '/category/$slug'
    | '/order-success/$id'
    | '/product/$id'
  id:
    | '__root__'
    | '/_shop'
    | '/admin'
    | '/_shop/about'
    | '/_shop/cart'
    | '/_shop/categories'
    | '/_shop/checkout'
    | '/_shop/contact'
    | '/_shop/login'
    | '/_shop/new-arrivals'
    | '/_shop/profile'
    | '/_shop/refund-policy'
    | '/_shop/search'
    | '/_shop/shipping-policy'
    | '/_shop/terms'
    | '/_shop/track-order'
    | '/_shop/wishlist'
    | '/admin/categories'
    | '/admin/orders'
    | '/admin/products'
    | '/_shop/'
    | '/admin/'
    | '/_shop/category/$slug'
    | '/_shop/order-success/$id'
    | '/_shop/product/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShopRoute: typeof ShopRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shop': {
      id: '/_shop'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shop/': {
      id: '/_shop/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/about': {
      id: '/_shop/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof ShopAboutRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/cart': {
      id: '/_shop/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof ShopCartRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/categories': {
      id: '/_shop/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof ShopCategoriesRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/checkout': {
      id: '/_shop/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof ShopCheckoutRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/contact': {
      id: '/_shop/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ShopContactRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/login': {
      id: '/_shop/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof ShopLoginRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/new-arrivals': {
      id: '/_shop/new-arrivals'
      path: '/new-arrivals'
      fullPath: '/new-arrivals'
      preLoaderRoute: typeof ShopNewArrivalsRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/profile': {
      id: '/_shop/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ShopProfileRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/refund-policy': {
      id: '/_shop/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof ShopRefundPolicyRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/search': {
      id: '/_shop/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof ShopSearchRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/shipping-policy': {
      id: '/_shop/shipping-policy'
      path: '/shipping-policy'
      fullPath: '/shipping-policy'
      preLoaderRoute: typeof ShopShippingPolicyRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/terms': {
      id: '/_shop/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof ShopTermsRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/track-order': {
      id: '/_shop/track-order'
      path: '/track-order'
      fullPath: '/track-order'
      preLoaderRoute: typeof ShopTrackOrderRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/wishlist': {
      id: '/_shop/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof ShopWishlistRouteImport
      parentRoute: typeof ShopRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_shop/category/$slug': {
      id: '/_shop/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof ShopCategorySlugRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/order-success/$id': {
      id: '/_shop/order-success/$id'
      path: '/order-success/$id'
      fullPath: '/order-success/$id'
      preLoaderRoute: typeof ShopOrderSuccessIdRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/product/$id': {
      id: '/_shop/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ShopProductIdRouteImport
      parentRoute: typeof ShopRoute
    }
  }
}

interface ShopRouteChildren {
  ShopAboutRoute: typeof ShopAboutRoute
  ShopCartRoute: typeof ShopCartRoute
  ShopCategoriesRoute: typeof ShopCategoriesRoute
  ShopCheckoutRoute: typeof ShopCheckoutRoute
  ShopContactRoute: typeof ShopContactRoute
  ShopLoginRoute: typeof ShopLoginRoute
  ShopNewArrivalsRoute: typeof ShopNewArrivalsRoute
  ShopProfileRoute: typeof ShopProfileRoute
  ShopRefundPolicyRoute: typeof ShopRefundPolicyRoute
  ShopSearchRoute: typeof ShopSearchRoute
  ShopShippingPolicyRoute: typeof ShopShippingPolicyRoute
  ShopTermsRoute: typeof ShopTermsRoute
  ShopTrackOrderRoute: typeof ShopTrackOrderRoute
  ShopWishlistRoute: typeof ShopWishlistRoute
  ShopIndexRoute: typeof ShopIndexRoute
  ShopCategorySlugRoute: typeof ShopCategorySlugRoute
  ShopOrderSuccessIdRoute: typeof ShopOrderSuccessIdRoute
  ShopProductIdRoute: typeof ShopProductIdRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopAboutRoute: ShopAboutRoute,
  ShopCartRoute: ShopCartRoute,
  ShopCategoriesRoute: ShopCategoriesRoute,
  ShopCheckoutRoute: ShopCheckoutRoute,
  ShopContactRoute: ShopContactRoute,
  ShopLoginRoute: ShopLoginRoute,
  ShopNewArrivalsRoute: ShopNewArrivalsRoute,
  ShopProfileRoute: ShopProfileRoute,
  ShopRefundPolicyRoute: ShopRefundPolicyRoute,
  ShopSearchRoute: ShopSearchRoute,
  ShopShippingPolicyRoute: ShopShippingPolicyRoute,
  ShopTermsRoute: ShopTermsRoute,
  ShopTrackOrderRoute: ShopTrackOrderRoute,
  ShopWishlistRoute: ShopWishlistRoute,
  ShopIndexRoute: ShopIndexRoute,
  ShopCategorySlugRoute: ShopCategorySlugRoute,
  ShopOrderSuccessIdRoute: ShopOrderSuccessIdRoute,
  ShopProductIdRoute: ShopProductIdRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

interface AdminRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShopRoute: ShopRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
